# Generated by Django 4.1.5 on 2023-03-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yaroslav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='posters',
            field=models.ManyToManyField(blank=True, to='Yaroslav.poster'),
        ),
    ]
